apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: minimal-release-test
  annotations:
    tekton.dev/tags: release
  labels:
    appstudio.openshift.io/release-pipeline: "true"
spec:
  description: Minimal pipeline for testing ReleasePlan integration
  workspaces:
    - name: release-workspace
  results:
    - name: TEST_OUTPUT
      value: "$(tasks.test-output-simulate.results.TEST_OUTPUT)"
  tasks:
    - name: hello
      taskSpec:
        steps:
          - name: say-hello
            image: registry.access.redhat.com/ubi8/ubi-minimal
            script: |
              #!/bin/sh
              echo "Hello from a minimal pipeline!"
          # - name: fail-test
          #   image: registry.access.redhat.com/ubi8/ubi-minimal
          #   script: |
          #     #!/bin/sh
          #     echo "Simulating test failure"
          #     exit 1  # Simulate failure
    - name: goodbye
      runAfter:
        - hello
      taskSpec:
        steps:
          - name: say-goodbye
            image: registry.access.redhat.com/ubi8/ubi-minimal
            script: |
              #!/bin/sh
              echo "Goodbye from a minimal pipeline!"
    - name: test-output-simulate
      runAfter:
        - goodbye
      taskSpec:
        results:
          - name: TEST_OUTPUT
            description: "Test result output"
        steps:
          - name: simulate-error
            image: registry.access.redhat.com/ubi8/ubi-minimal
            script: |
              #!/bin/sh
              # echo "ERROR: Simulated test failure" > $(results.TEST_OUTPUT.path)
              timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
              cat <<EOF > $(results.TEST_OUTPUT.path)
              {
                "result": "ERROR",
                "namespace": "example-namespace",
                "timestamp": "$timestamp",
                "successes": 0,
                "failures": 1,
                "warnings": 0,
                "note": "Simulated failure for testing TEST_OUTPUT reporting"
              }
              EOF
              exit 0  # Task exits with success, but logs an error in TEST_OUTPUT
          # - name: simulate-skipped
          #   image: registry.access.redhat.com/ubi8/ubi-minimal
          #   script: |
          #     #!/bin/sh

          #     timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          #     cat <<EOF > $(results.TEST_OUTPUT.path)
          #     {
          #       "result": "SKIPPED",
          #       "namespace": "example-namespace",
          #       "timestamp": "$timestamp",
          #       "successes": 0,
          #       "failures": 1,
          #       "warnings": 0,
          #       "note": "Simulated skipped for testing TEST_OUTPUT reporting"
          #     }
          #     EOF
          #     exit 0
          # - name: simulate-warning
          #   image: registry.access.redhat.com/ubi8/ubi-minimal
          #   script: |
          #     #!/bin/sh

          #     timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          #     cat <<EOF > $(results.TEST_OUTPUT.path)
          #     {
          #       "result": "WARNING",
          #       "namespace": "example-namespace",
          #       "timestamp": "$timestamp",
          #       "successes": 0,
          #       "failures": 1,
          #       "warnings": 0,
          #       "note": "Simulated WARNING for testing TEST_OUTPUT reporting"
          #     }
          #     EOF
          #     exit 0
          # - name: simulate-failure
          #   image: registry.access.redhat.com/ubi8/ubi-minimal
          #   script: |
          #     #!/bin/sh

          #     timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          #     cat <<EOF > $(results.TEST_OUTPUT.path)
          #     {
          #       "result": "FAILURE",
          #       "namespace": "example-namespace",
          #       "timestamp": "$timestamp",
          #       "successes": 0,
          #       "failures": 1,
          #       "warnings": 0,
          #       "note": "Simulated FAILURE for testing TEST_OUTPUT reporting"
          #     }
          #     EOF
          #     exit 0
          # - name: simulate-success
          #   image: registry.access.redhat.com/ubi8/ubi-minimal
          #   script: |
          #     #!/bin/sh

          #     timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          #     cat <<EOF > $(results.TEST_OUTPUT.path)
          #     {
          #       "result": "SUCCESS",
          #       "namespace": "example-namespace",
          #       "timestamp": "$timestamp",
          #       "successes": 0,
          #       "failures": 1,
          #       "warnings": 0,
          #       "note": "Simulated SUCCESS for testing TEST_OUTPUT reporting"
          #     }
          #     EOF
          #     exit 0
