apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: minimal-release-test
  annotations:
    tekton.dev/tags: release
  labels:
    appstudio.openshift.io/release-pipeline: "true"
spec:
  description: Minimal pipeline for testing ReleasePlan integration
  workspaces:
    - name: release-workspace
  tasks:
    - name: hello
      taskSpec:
        steps:
          - name: say-hello
            image: registry.access.redhat.com/ubi8/ubi-minimal
            script: |
              #!/bin/sh
              echo "Hello from a minimal pipeline!"
    - name: goodbye
      runAfter:
        - hello
      taskSpec:
        steps:
          - name: say-goodbye
            image: registry.access.redhat.com/ubi8/ubi-minimal
            script: |
              #!/bin/sh
              echo "Goodbye from a minimal pipeline!"
