# apiVersion: tekton.dev/v1
# kind: Task
# metadata:
#   name: idle-final-task
# spec:
#   steps:
#     - name: wait
#       image: registry.access.redhat.com/ubi8/ubi-minimal
#       script: |
#         #!/bin/sh
#         echo "Trying to run a final task..."
#         sleep 30
#       resources:
#         requests:
#           memory: "2Ti"
#           cpu: "999"
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: idle-final-task
spec:
  params:
    - name: enable-finalizer
  steps:
    - name: maybe-idle
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |
        sleep 10
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: simulate-long-running-time-release
  annotations:
    tekton.dev/tags: release
  labels:
    appstudio.openshift.io/release-pipeline: "true"
spec:
  description: Minimal pipeline for testing ReleasePlan integration
  params:
    - name: enable-finalizer
      type: string
      default: "true"
  workspaces:
    - name: release-workspace
  results:
    - name: TEST_OUTPUT
      value: "$(tasks.test-output.results.TEST_OUTPUT)"
  tasks:
    - name: hello
      taskSpec:
        steps:
          - name: say-hello
            image: registry.access.redhat.com/ubi8/ubi-minimal
            script: |
              #!/bin/sh
              echo "Hello from a minimal pipeline!"

    - name: goodbye
      runAfter:
        - hello
      taskSpec:
        steps:
          - name: say-goodbye
            image: registry.access.redhat.com/ubi8/ubi-minimal
            script: |
              #!/bin/sh
              echo "Goodbye from a minimal pipeline!"

    - name: conditionally-skipped-task
      runAfter:
        - goodbye
      when:
        - input: "false"
          operator: in
          values: ["true"]
      taskSpec:
        steps:
          - name: should-not-run
            image: registry.access.redhat.com/ubi8/ubi-minimal
            script: |
              echo "This task should be skipped!"

    - name: test-output
      runAfter:
        - conditionally-skipped-task
      taskSpec:
        results:
          - name: TEST_OUTPUT
        steps:
          - name: output-result
            image: registry.access.redhat.com/ubi8/ubi-minimal
            script: |
              #!/bin/sh
              echo '{"result": "SUCCESS"}' > $(results.TEST_OUTPUT.path)

    # - name: test-output-simulate
    #   runAfter:
    #     - conditionally-skipped-task
    #   taskSpec:
    #     results:
    #       - name: TEST_OUTPUT
    #         description: "Test result output"
    #     steps:
    #       - name: simulate-error
    #         image: registry.access.redhat.com/ubi8/ubi-minimal
    #         script: |
    #           #!/bin/sh
    #           timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    #           cat <<EOF > $(results.TEST_OUTPUT.path)
    #           {
    #             "result": "ERROR",
    #             "namespace": "example-namespace",
    #             "timestamp": "$timestamp",
    #             "successes": 0,
    #             "failures": 1,
    #             "warnings": 0,
    #             "note": "Simulated failure for testing TEST_OUTPUT reporting"
    #           }
    #           EOF
    #           exit 0
    # finally:
    #   - name: long-finalizer
    #     taskSpec:
    #       steps:
    #         - name: final-cleanup
    #           image: registry.access.redhat.com/ubi8/ubi-minimal
    #           script: |
    #             #!/bin/sh
    #             echo "Starting long final task..."
    #             sleep 600  # Simulate long-running final step
    #             echo "Final task done."

    # - name: bad-final-task
    #   taskSpec:
    #     steps:
    #       - name: oops
    #         image: "nonexistent/image:latest" # This image doesn't exist
    #         script: |
    #           #!/bin/sh
    #           echo "This will never run"

    # - name: sneaky-final
    #   when:
    #     - input: "false"
    #       operator: in
    #       values: ["true"]
    #   taskSpec:
    #     steps:
    #       - name: sneaky-step
    #         image: registry.access.redhat.com/ubi8/ubi-minimal
    #         script: |
    #           #!/bin/sh
    #           echo "This should never run"

    # - name: idle-final-task
    #   taskRef:
    #     name: idle-final-task
  finally:
    - name: idle-final-task
      when:
        - input: "$(params.enable-finalizer)"
          operator: in
          values: ["true"]
      params:
        - name: enable-finalizer
          value: "$(params.enable-finalizer)"
      taskRef:
        name: idle-final-task
      taskRunTemplate:
        serviceAccountName: does-not-exist
